<?php

namespace FilRougeBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
  public function getSearchResults($key)
    {
      $qb = $this->createQueryBuilder('e');
      $qb ->select('e')
          ->where('e.title LIKE :key')
          ->setParameter('key', '%'.$key.'%');
      $results = $qb->getQuery()->getResult();
      return $results;
    }
}
