<?php

namespace Ideato\StarRatingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
  public function byIdAndType($contentId, $contentType)
  {
    $qb = $this->createQueryBuilder('r');
    $qb->where('r.contentId = :contentId')
         ->setParameter('contentId', $contentId)
       ->andWhere('r.contentType = :contentType')
         ->setParameter('contentType', $contentType)
    ;
    return $qb
      ->getQuery()
      ->getSingleResult()
    ;
  }
}
